language: node_js
before_script:
    - sh -e /etc/init.d/xvfb start
    - git clone https://github.com/mozilla/addon-sdk
env:
    - DISPLAY=':99.0'
script: /bin/sh -c 'cd addon-sdk; . bin/activate; cd ..; cfx test .'
