// Generated by CoffeeScript 1.4.0
(function() {
  var OptionsStore, SiteOptions;

  OptionsStore = require("./store").OptionsStore;

  SiteOptions = require("./options").SiteOptions;

  exports['test new'] = function(assert) {
    var store;
    store = new OptionsStore(new SiteOptions());
    assert.strictEqual(0, store.mappingCount());
    store.getOptions("test");
    assert.strictEqual(1, store.mappingCount());
    store.getOptions("test");
    return assert.strictEqual(1, store.mappingCount());
  };

  require("sdk/test").run(exports);

}).call(this);
