// Generated by CoffeeScript 1.4.0
(function() {
  var SiteOptions;

  SiteOptions = require("./options").SiteOptions;

  exports['test constructor'] = function(assert) {
    var options;
    options = new SiteOptions();
    assert.strictEqual(36, options.private_key.length);
    assert.strictEqual(12, options.length);
    assert.strictEqual("alnum", options.char_mode);
    assert.strictEqual(null, options.site_tag);
    return assert.strictEqual(0, options.bump);
  };

  exports['test generatePrivateKey'] = function(assert) {
    var result;
    result = SiteOptions.generatePrivateKey();
    assert.equal("string", typeof result);
    return assert.equal(36, result.length);
  };

  exports['test getFullTag'] = function(assert) {
    var options;
    options = new SiteOptions("xxx", 12, "alnum", null);
    assert.strictEqual("generic", options.getFullTag());
    options = new SiteOptions("xxx", 12, "alnum", "thunderk");
    assert.strictEqual("thunderk", options.getFullTag());
    options = new SiteOptions("xxx", 12, "alnum", "thunderk", 0);
    assert.strictEqual("thunderk", options.getFullTag());
    options = new SiteOptions("xxx", 12, "alnum", "thunderk", 1);
    return assert.strictEqual("thunderk:1", options.getFullTag());
  };

  require("sdk/test").run(exports);

}).call(this);
