// Generated by CoffeeScript 1.4.0
(function() {
  var PasswordHasher, SiteOptions;

  SiteOptions = require("./options").SiteOptions;

  PasswordHasher = require("./hasher").PasswordHasher;

  exports['test getHash'] = function(assert) {
    var config, hasher, result;
    config = new SiteOptions("5DB6DAF0-8F1D-4FB2-9845-F3E2390FB5BB", 12, "alnum", "test");
    hasher = new PasswordHasher;
    result = hasher.getHash(config, "password");
    return assert.strictEqual("JNiDEjUp0oKs", result, "Resulting hash differs");
  };

  require("sdk/test").run(exports);

}).call(this);
