// Generated by CoffeeScript 1.4.0
(function() {
  var HashLockFirefoxWorker, PageMod, Panel, Widget, config_panel, data, page_mod, tabs, widget, worker;

  Widget = require("sdk/widget").Widget;

  Panel = require("sdk/panel").Panel;

  data = require("sdk/self").data;

  PageMod = require("sdk/page-mod").PageMod;

  tabs = require("sdk/tabs");

  HashLockFirefoxWorker = require("./worker/firefox").HashLockFirefoxWorker;

  config_panel = null;

  page_mod = null;

  widget = null;

  worker = null;

  exports.main = function() {
    worker = new HashLockFirefoxWorker();
    config_panel = Panel({
      width: 400,
      height: 200,
      contentURL: data.url('popup.html'),
      contentScriptFile: [data.url("jquery-2.1.0.min.js"), data.url("content-script/common.js"), data.url("content-script/firefox.js")]
    });
    worker.addPeer(config_panel.port);
    widget = new Widget({
      id: "hashlock-widget",
      label: "HashLock",
      contentURL: data.url("images/hashlock.png"),
      panel: config_panel
    });
    return page_mod = PageMod({
      include: "*",
      contentScriptFile: [data.url("jquery-2.1.0.min.js"), data.url("content-script/common.js"), data.url("content-script/firefox.js")],
      onAttach: function(page_worker) {
        worker.addPeer(page_worker.port);
        return page_worker.on('detach', function() {
          return worker.removePeer(page_worker.port);
        });
      }
    });
  };

}).call(this);
