// Generated by CoffeeScript 1.4.0
(function() {
  var generatePrivateKey, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  generatePrivateKey = function() {
    var guid;
    guid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      var r, v;
      r = Math.random() * 16 | 0;
      v = c === 'x' ? r : r & 0x3 | 0x8;
      return v.toString(16);
    });
    return guid.toUpperCase();
  };

  root.SiteOptions = (function() {

    function SiteOptions(private_key, length, char_mode, site_tag, bump) {
      this.private_key = private_key != null ? private_key : null;
      this.length = length != null ? length : 12;
      this.char_mode = char_mode != null ? char_mode : "alnum";
      this.site_tag = site_tag != null ? site_tag : null;
      this.bump = bump != null ? bump : 0;
      if (!this.private_key) {
        this.private_key = generatePrivateKey();
        console.log("Generated private key : " + this.private_key);
      }
    }

    SiteOptions.generatePrivateKey = generatePrivateKey;

    SiteOptions.prototype.getFullTag = function() {
      if (!this.site_tag) {
        return "generic";
      } else if (this.bump > 0) {
        return "" + this.site_tag + ":" + this.bump;
      } else {
        return this.site_tag;
      }
    };

    return SiteOptions;

  })();

}).call(this);
