// Generated by CoffeeScript 1.4.0
(function() {

  exports.OptionsStore = (function() {

    function OptionsStore(globalOptions) {
      this.globalOptions = globalOptions;
      this.mapping = {};
    }

    OptionsStore.prototype.mappingCount = function() {
      return Object.keys(this.mapping).length;
    };

    OptionsStore.prototype.setGlobalOptions = function(options) {
      return this.globalOptions = options;
    };

    OptionsStore.prototype.getOptions = function(sitetag) {
      var options;
      options = this.mapping[sitetag];
      if (!(options != null)) {
        options = this.globalOptions.getCopy(sitetag);
        this.mapping[sitetag] = options;
      }
      return options;
    };

    return OptionsStore;

  })();

}).call(this);
